apiVersion: v1
kind: Deployment
metadata:
  labels:
    name: simple-react-app
  name: simple-app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: simple-app-pod
    spec:
      containers:
      - image: plmnko098/simple-react-app
        name: simple-app
        ports:
        - name: simple-app
          containerPort: 3000      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: simple-service
  name: simple-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    name: simple-app-pod
